apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority-data: <base64-ca-cert>
      server: https://127.0.0.1:54888                # your cluster endpoint
    name: docker-desktop
contexts:
  - context:
      cluster: docker-desktop
      user: jenkins-sa
    name: jenkins-context
current-context: jenkins-context
users:
  - name: jenkins-sa
    user:
      token: <copied-token>                          # from jenkins-sa-secret
